bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'bib'

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

vocabs/urls.py
from django.conf.urls import url
from . import views
from . import import_views
from . import dal_views
from .models import SkosLabel, SkosConcept, SkosConceptScheme

app_name = 'vocabs'


urlpatterns = [
    url(r'^$', views.SkosConceptListView.as_view(), name='skosconcept_list'),
    url(r'^concepts/browse/$', views.SkosConceptListView.as_view(), name='browse_vocabs'),
    url(r'^import/$', import_views.import_skos, name='skos_import'),
    url(r'^import-from-csv/$', import_views.import_csv, name='skos_csv_import'),
    url(r'^(?P<pk>[0-9]+)$', views.SkosConceptDetailView.as_view(), name='skosconcept_detail'),
    url(r'^create/$', views.SkosConceptCreate.as_view(), name='skosconcept_create'),
    url(r'^update/(?P<pk>[0-9]+)$', views.SkosConceptUpdate.as_view(), name='skosconcept_update'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.SkosConceptDelete.as_view(), name='skosconcept_delete'),
    url(r'^scheme/$', views.SkosConceptSchemeListView.as_view(), name='browse_schemes'),
    url(
        r'^scheme/(?P<pk>[0-9]+)$', views.SkosConceptSchemeDetailView.as_view(),
        name='skosconceptscheme_detail'),
    url(
        r'^scheme/create/$', views.SkosConceptSchemeCreate.as_view(),
        name='skosconceptscheme_create'),
    url(
        r'^scheme/update/(?P<pk>[0-9]+)$', views.SkosConceptSchemeUpdate.as_view(),
        name='skosconceptscheme_update'),
    url(
        r'^scheme/delete/(?P<pk>[0-9]+)$',
        views.SkosConceptSchemeDelete.as_view(),
        name='skosconceptscheme_delete',
    ),
    url(r'^label/$', views.SkosLabelListView.as_view(), name='browse_skoslabels'),
    url(
        r'^label/(?P<pk>[0-9]+)$', views.SkosLabelDetailView.as_view(),
        name='skoslabel_detail'),
    url(
        r'^label/create/$', views.SkosLabelCreate.as_view(),
        name='skoslabel_create'),
    url(
        r'^label/update/(?P<pk>[0-9]+)$', views.SkosLabelUpdate.as_view(),
        name='skoslabel_update'),
    url(
        r'^skoslabel/delete/(?P<pk>[0-9]+)$',
        views.SkosLabelDelete.as_view(),
        name='skoslabel_delete',
    ),
]

vocabs/forms.py
from dal import autocomplete
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, Div, MultiField, HTML
from crispy_forms.bootstrap import *
from .models import SkosConcept, SkosConceptScheme, SkosLabel


class GenericFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(GenericFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.add_input(Submit('Filter', 'search'))


class UploadFileForm(forms.Form):
    file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'import'),)


class SkosConceptFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(SkosConceptFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Accordion(
                AccordionGroup(
                    'Basic search options',
                    'pref_label',
                    css_id="basic_search_fields"
                ),
                AccordionGroup(
                    'Advanced search',
                    'scheme',
                    css_id="more"
                    ),
                )
            )


class SkosConceptForm(forms.ModelForm):
    class Meta:
        model = SkosConcept
        fields = "__all__"
        widgets = {
            'label': autocomplete.ModelSelect2Multiple(url='vocabs-ac:skoslabel-autocomplete'),
            'skos_broader': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_narrower': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_related': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_broadmatch': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_exactmatch': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_closematch': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'scheme': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconceptscheme-autocomplete'
            )
        }

    def __init__(self, *args, **kwargs):
        super(SkosConceptForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class SkosConceptSchemeForm(forms.ModelForm):
    class Meta:
        model = SkosConceptScheme
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(SkosConceptSchemeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class SkosConceptSchemeFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(SkosConceptSchemeFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Accordion(
                AccordionGroup(
                    'Basic search options',
                    'dc_title',
                    css_id="basic_search_fields"
                ),
                AccordionGroup(
                    'Advanced search',
                    'dct_creator',
                    css_id="more"
                    ),
                )
            )


class SkosLabelForm(forms.ModelForm):
    class Meta:
        model = SkosLabel
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(SkosLabelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class SkosLabelFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(SkosLabelFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))

vocabs/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django_tables2 import SingleTableView, RequestConfig
from .models import SkosConcept, SkosConceptScheme, SkosLabel
from .forms import *
from .tables import SkosConceptTable, SkosConceptSchemeTable, SkosLabelTable
from .filters import SkosConceptListFilter, SkosConceptSchemeListFilter, SkosLabelListFilter
from webpage.utils import GenericListView, BaseCreateView, BaseUpdateView


class SkosConceptListView(GenericListView):
    model = SkosConcept
    table_class = SkosConceptTable
    filter_class = SkosConceptListFilter
    formhelper_class = SkosConceptFormHelper
    init_columns = [
        'id',
        'pref_label',
        'broader_concept',
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosConceptListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosConceptDetailView(DetailView):

    model = SkosConcept
    template_name = 'vocabs/skosconcept_detail.html'


class SkosConceptCreate(BaseCreateView):

    model = SkosConcept
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptCreate, self).dispatch(*args, **kwargs)


class SkosConceptUpdate(BaseUpdateView):

    model = SkosConcept
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptUpdate, self).dispatch(*args, **kwargs)


class SkosConceptDelete(DeleteView):
    model = SkosConcept
    template_name = 'vocabs/confirm_delete.html'
    success_url = reverse_lazy('vocabs:browse_vocabs')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptDelete, self).dispatch(*args, **kwargs)


#####################################################
#   ConceptScheme
#####################################################


class SkosConceptSchemeListView(GenericListView):
    model = SkosConceptScheme
    table_class = SkosConceptSchemeTable
    filter_class = SkosConceptSchemeListFilter
    formhelper_class = SkosConceptSchemeFormHelper
    init_columns = [
        'id',
        'dc_title',
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosConceptSchemeDetailView(DetailView):

    model = SkosConceptScheme
    template_name = 'vocabs/skosconceptscheme_detail.html'

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeDetailView, self).get_context_data(**kwargs)
        context["concepts"] = SkosConcept.objects.filter(scheme=self.kwargs.get('pk'))
        return context


class SkosConceptSchemeCreate(BaseCreateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeCreate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeUpdate(BaseUpdateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeUpdate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeDelete(DeleteView):
    model = SkosConceptScheme
    template_name = 'vocabs/confirm_delete.html'
    success_url = reverse_lazy('vocabs:browse_schemes')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeDelete, self).dispatch(*args, **kwargs)


###################################################
# SkosLabel
###################################################


class SkosLabelListView(GenericListView):
    model = SkosLabel
    table_class = SkosLabelTable
    filter_class = SkosLabelListFilter
    formhelper_class = SkosLabelFormHelper
    init_columns = [
        'id',
        'label',
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosLabelListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosLabelDetailView(DetailView):

    model = SkosLabel
    template_name = 'vocabs/skoslabel_detail.html'


class SkosLabelCreate(BaseCreateView):

    model = SkosLabel
    form_class = SkosLabelForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosLabelCreate, self).dispatch(*args, **kwargs)


class SkosLabelUpdate(BaseUpdateView):

    model = SkosLabel
    form_class = SkosLabelForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosLabelUpdate, self).dispatch(*args, **kwargs)


class SkosLabelDelete(DeleteView):
    model = SkosLabel
    template_name = 'vocabs/confirm_delete.html'
    success_url = reverse_lazy('vocabs:browse_skoslabels')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosLabelDelete, self).dispatch(*args, **kwargs)

vocabs/templates/vocabs/confirm_delete.html
{% extends "vocabs/plain_for_delete.html" %}
{% block content %}
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
            <h3 class="modal-title">Confirm delete</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
            </div>
            <div class="modal-body">
                <form action="" method="post">{% csrf_token %}
                    <h4>Are you sure you want to delete :<br /> <strong>{{ object }}</strong> ?</h4><br />
                    <a href="javascript:history.back()"><input class="btn btn-default" type="button" value="cancel"/></a>
                    <input  class="btn btn-danger" type="submit" value="yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
    <script type="text/javascript">
        $(window).load(function(){
            $('#myModal').modal('show');
        });
    </script>
{% endblock scripts %}

vocabs/templates/vocabs/import_skos.html
{% extends "webpage/base.html" %}
{% block Title %} Import SKOS {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<div class="card">
    <div class="card-header">
        <h1 style="text-align: center;">Import SKOS</h1>
    </div>
    <div class="card-body">
        <h2 style="text-align: center;">{{ worked }}</h2><br />
        {% crispy form %}
        </div>
    </div>
</div>
{% endblock content %}

vocabs/templates/vocabs/skosconcept_detail.html
{% extends "webpage/base.html" %}
{% block Title %}{{ object }}{% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skosconcept_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>SkosConcept:</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skosconcept_update' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skosconcept_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skosconcept_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-2">
                    <div class="card">
                        <div class="card-header">skos:broader</div>
                        <div class="card-body">
                            <h3>{{ object.broader_concept }}</h3>
                            {% for x in object.get_broader %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">skos:related</div>
                        <div class="card-body">
                            {% for x in object.skos_related.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">skos:broadMatch</div>
                        <div class="card-body">
                            {% for x in object.skos_broadmatch.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">skos:closeMatch</div>
                        <div class="card-body">
                            {% for x in object.skos_closematch.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                            {% for x in object.closematch.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">skos:exactMatch</div>
                        <div class="card-body">
                            {% for x in object.skos_exactmatch.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="card">

                        <div class="card-body">
                            <legend>about</legend>
                            <table class="table table-bordered table-striped table-hover">
                                <tr>
                                    <td>skos:prefLabel| @{{ object.pref_label_lang }}</td>
                                    <td>{{ object.pref_label }} </td>
                                </tr>
                                {% if object.definition %}
                                    <tr>
                                        <td>skos:definition | @{{ object.definition_lang }}</td>
                                        <td>{{ object.definition }}</td>
                                    </tr>
                                {% endif %}
                                {% if object.scheme.all %}
                                    <tr>
                                        <td>skos:inScheme</td>
                                        <td>
                                            {% for x in object.scheme.all %}
                                                <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                                                {% if user.is_authenticated %}
                                                    <a href="{% url 'vocabs:skosconceptscheme_update' pk=x.id %}">
                                                        <i class="far fa-edit" title="edit"></i>
                                                    </a>
                                                {% endif %}<br/>
                                            {% endfor %}
                                        </td>
                                    </tr>
                                {% endif %}
                                {% if object.name_reverse %}
                                    <tr>
                                        <tr>
                                            <td>Reverse Name</td>
                                            <td>
                                                {{ object.name_reverse }}
                                            </td>
                                        </tr>
                                        <td>Labels</td>
                                        <td>
                                            {% for x in object.label.all %} {{ x }}
                                                {% if user.is_authenticated %}
                                                    <a href="{% url 'vocabs:skoslabel_update' pk=x.id %}">
                                                        <i class="far fa-edit" title="edit"></i>
                                                    </a>
                                                {% endif %}<br />
                                            {% endfor %}
                                        </td>
                                    </tr>
                                {% endif %}
                                {% if object.legacy_id %}
                                    <tr>
                                        <td>legacy id</td>
                                        <td>{{ object.legacy_id }}</td>
                                    </tr>
                                {% endif %}
                            </table>
                            <legend>
                                related concepts
                            </legend>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="card">
                        <div class="card-header">skos:narrower</div>
                        <div class="card-body">
                            {% for x in object.narrower_concepts.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class ="btn btn-danger" href="{% url 'vocabs:skosconcept_delete' pk=object.id %}">delete</a>
</div>
{% endblock content %}

vocabs/templates/vocabs/skosconcept_filter.html
{% extends "vocabs/generic_list.html" %}
{% block list_title %}Browse SkosConcepts{% endblock %}
{% block create_button %}
{% if user.is_authenticated %}
<div>
    <a class ="btn btn-primary"  href="{% url 'vocabs:skosconcept_create' %}">
        create new concept
    </a>
</div>
{% endif %}
{% endblock %}
{% block reset_button %}
    <a class ="btn btn-outline-secondary" href="{% url 'vocabs:browse_vocabs' %}">reset search</a>
{% endblock %}

vocabs/templates/vocabs/skosconceptscheme_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skosconceptscheme_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>SkosConceptScheme:</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skosconceptscheme_update' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skosconceptscheme_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skosconceptscheme_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <div class="card-body">
            <legend>
                related concepts
            </legend>
                {% for x in object.has_concepts.all %}
                    <li>
                        <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                    </li>
                {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skoslabel_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skoslabel_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>SkosLabel:</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skoslabel_update' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skoslabel_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skoslabel_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <tr>
                    <th>Label</th>
                    <td>{{ object.label }}</td>
                </tr>
                <tr>
                    <th>Label type</th>
                    <td>{{ object.label_type }}</td>
                </tr>
                <tr>
                    <th>IsoCode</th>
                    <td>{{ object.isoCode }}</td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}