bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'bib'

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

webpage/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

app_name = 'webpage'

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^favicon\.ico$', favicon_view),
    url(r'^$', views.GenericWebpageView.as_view(), name="start"),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^(?P<template>[\w-]+)/$', views.GenericWebpageView.as_view(), name='staticpage'),
]

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class form_user_login(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(form_user_login, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'login'))

webpage/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from .forms import form_user_login


class GenericWebpageView(TemplateView):
    template_name = 'webpage/index.html'

    def get_template_names(self):
        template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        try:
            loader.select_template([template_name])
            template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        except:
            template_name = "webpage/index.html"
        return [template_name]


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get('next', '/'))
            return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render_to_response('webpage/user_logout.html')

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block title %} Allgemein {% endblock %}
{% block content %}
<!-- end header -->
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <ul class="breadcrumb">
        <li><a href="{% url 'webpage:start' %}"><i class="fa fa-home" style="color:white"></i></a><i class="icon-angle-right"></i></li>
        <li><a href="#" style="color:white;">Projekt</a><i class="icon-angle-right"></i></li>
        <li class="active">Allgemein</li>
      </ul>
    </div>
  </div>
</div>

<div class="container" style="margin-top:25px;">
  <div class="row">
    <div class="col-lg-12">
      <div class="row">

        <div class="col-lg-3">
          <div class="box-gray ">
            <h5><i class="fa fa-camera fa" style="color: #331165" aria-hidden="true"></i> Gallerie</h5>
            <ul class="images">
              <div class="row">
                <div class="col-lg-12" style="">
                    <img class="img-responsive gallery-items" originalUrl="{% static 'webpage/img/about01.png' %}" src="{% static 'webpage/img/about01.png' %}" style="padding-top:5px;"  alt="">
                    <span style="font-size:9px;"> Abbildung 1:</span>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12" style="">
                    <img originalUrl="{% static 'webpage/img/about02.png' %}" src="{% static 'webpage/img/about02.png' %}"  style="padding-top:5px;" class="img-responsive gallery-items" alt="">
                    <span style="font-size:9px;"> Abbildung 2:</span>
                </div>
            </div>
            <div class="row">
              <div class="col-lg-12" style="">
                  <img originalUrl="{% static 'webpage/img/about03_full.png' %}" src="{% static 'webpage/img/about03.png' %}"  style="padding-top:5px;" class="img-responsive gallery-items" alt="">
                  <span style="font-size:9px;"> Abbildung 3:</span>
              </div>
            </div>
          </ul>

          </div>
        </div>


        <div class="col-lg-9">
          <div class="box-gray aligncenter">
            <h2>Thunau am Kamp – Eine befestigte Höhensiedlung</h2>
            <hr width="10%">
            <p>
              Die archäologischen Grabungen in Gars-Thunau haben schon eine lange Tradition und haben zahlreiche Befunde und Funde aus den verschiedensten Epochen zu Tage gefördert. Im Zentrum dieses Digitalisierungsprojektes stehen die Grabungskampagnen von em.o. Univ.-Prof. Dr. phil. Dr.h.c. Herwig Friesinger aus den Jahren 1965-2003. Der großteil der Funde aus diesen Kampagnen datiert in die Urnenfelderkultur (1300-800 v. Chr.) der späten Bronzezeit. Das Zentrum der Fundstelle bildet der sogenannte „Schanzberg“ auf einem Höhenrücken oberhalb der Gemeinde Thunau, 80 km nordwestlich von Wien.
            </p>
            <p>
                Aufgrund der Langjährigen Grabungstätigkeit und den vielen Kleinprojekten und Ausstellungen ist eine große Menge an analogen Daten, wie Fotos, Bilder, Textmaterial für Austellungen, Zeitungsberichte, Grabungsdokumentation, … angefallen. Um diese Menge an analogen Daten mit heutigen Methoden auswerten zu können werden nun die gesamten Dokumente digitalisiert und in einer Datenbank zusammengeführt. Damit soll gewährleistet sein, dass alle Informationen zu dieser Fundstelle, sowohl schon publiziertes wie auch bisher unbearbeitetes Material, an einem Ort abrufbar und damit einer weiteren Bearbeitung zur Verfügung stehen.
            </p>
            <br>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9773.144767553991!2d15.634944706592998!3d48.58908750087635!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDjCsDM1JzE0LjQiTiAxNcKwMzgnMjguNyJF!5e1!3m2!1sde!2sat!4v1530041277490" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>
        </div>


      </div>
    </div>
  </div>

</div>


{% endblock %}

webpage/templates/webpage/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load webpage_extras %}
{% load browsing_extras %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% projects_metadata 'title' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metaDescription %}
        <meta name="description" content="{{ metadata.description }}">
        <meta name="author" content="{{ metadata.author }}">
    {% endblock %}
    <!-- favicons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'webpage/img/favicon/apple-touch-icon.png' %}"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'webpage/img/favicon/favicon-32x32.png' %}"/>
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'webpage/img/favicon/favicon-16x16.png' %}"/>
        <link rel="manifest" href="{% static 'webpage/img/favicon/manifest.json' %}"/>
        <link rel="mask-icon" href="{% static 'webpage/img/favicon/safari-pinned-tab.svg' %}" color="#00aba9"/>
        <meta name="theme-color" content="#ffffff"/>
    <!--favicons end -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/bootstrap337/css/bootstrap.min.css' %}" />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'webpage/css/default.css' %}" />

    <link rel="stylesheet" href="{% static 'webpage/libraries/imageviewer/dist/viewer.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'webpage/css/style1.css' %}" />
    <!--scroll to top CSS -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}" />
    <!-- LESS -->
    <script type="text/javascript" src="{% static 'webpage/libraries/less/less.min.js' %}"></script>
    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'webpage/libraries/jquery/jquery.js' %}"></script>
    <!-- Popper -->
    <script type="text/javascript" src="{% static 'webpage/libraries/popper/popper.min.js' %}"></script>
    <!--scroll to top -->
    <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
    <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
    <script type="text/javascript">
        window.cookieconsent_options = {
            "message":"This website uses cookies to ensure you get the best experience on our website",
            "dismiss":"Got it!",
            "learnMore":"More info",
            "link":"{% url 'webpage:staticpage' template='imprint' %}",
            "theme":"dark-bottom"};
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
    <!-- End Cookie Consent plugin -->
    <!-- cool-share plugin http://tutorialzine.com/2014/08/cool-share-jquery-plugin/ -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/cool-share/plugin.css' %}" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet" />

    <script src="{% static 'webpage/libraries/cool-share/plugin.js' %}"></script>
    <!-- End fo cool-share -->
    <!-- Matomo -->
      <script type="text/javascript">
        var _paq = _paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
          var u="{% projects_metadata 'matomo_url' %}";
          _paq.push(['setTrackerUrl', u+'piwik.php']);
          _paq.push(['setSiteId', '{% projects_metadata "matomo_id" %}']);
          var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
          g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
      </script>
    <!-- End Matomo Code -->
    {% block scriptHeader %}
    {% endblock %}
</head>
<body role="">
  <header>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'webpage:start' %}"><span>D</span>okuplattform <span>T</span>hunau</a>
        </div>
        <div class="navbar-collapse collapse ">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'webpage:start' %}">Startseite</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle " data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Projekt <i class="fa fa-sort-down" aria-hidden="true"></i></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'webpage:staticpage' template='about' %}">Allgemein</a></li>
                <li><a href="{% url 'webpage:staticpage' template='excavation' %}">Grabung</a></li>
                <li><a href="{% url 'webpage:staticpage' template='digitisation' %}">Digitalisierung</a></li>
                <li><a href="{% url 'webpage:staticpage' template='views' %}">Ansichten</a></li>
              </ul>
            </li>
            <li><a href="{% url 'webpage:staticpage' template='database' %}">Kleinfunde DB</a></li>
            <li><a href="{% url 'webpage:staticpage' template='literature' %}">Literatur</a></li>
            <li><a href="{% url 'webpage:staticpage' template='contact' %}">Kontakt</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>


<section class="main-content">
    <div id="content">
      <!--   <div class="alert alert-warning alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Warning!</strong> Draft Version.
        </div> -->
        {% block content %}{% endblock %}
    </div>
</section>

<footer>
    <div class="container">
        <div class="row text-center">
            <div class="col-sm-4">
                <a href="https://www.oeaw.ac.at/acdh/" class="navlink" target="_blank">
                    <img src="{% static 'webpage/img/acdh_logo_02.png' %}" id="acdh-logo" alt="ACDH" title="Austrian Centre for Digital Humanities"/>
                </a>
            </div>
            <div class="col-sm-4">
                <a href="https://www.orea.oeaw.ac.at/" class="navlink" target="_blank">
                    <img src="{% static 'webpage/img/OREA_white.png' %}" id="orea-logo" alt="{{ metadata.github }}" title="Github source code"/>
                </a>
            </div>
            <div class="col-sm-4">
                <a href="http://www.mamuz.at/de/startseite" class="navlink" target="_blank">
                    <img src="{% static 'webpage/img/mamuz_logo.png' %}" id="mamuz-logo" alt="{{ metadata.github }}" title="Github source code"/>
                </a>
            </div>
        </div>
        <div class="row text-center">
          <div class="col-sm-4">
          </div>
          <div class="col-sm-4">
            <a href="{% url 'webpage:staticpage' template='terms' %}">Terms of Use</a><br>
            <a href="{% url 'webpage:staticpage' template='imprint' %}">Imprint</a>
          </div>
          <div class="col-sm-4">
          </div>
        </div>
      </div>
  </footer>
{% block scripts %}
<script type="text/javascript" src="{% static 'webpage/libraries/bootstrap337/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'webpage/libraries/bootstrap400/js/bootstrap-tab.js' %}"></script>
<script src="{% static 'webpage/libraries/imageviewer/dist/viewer.js' %}"></script>


<!--bootstrap-select must be after bootstrap js-->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css" />
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
<!-- cool share -->
<script type="text/javascript">
    $(function (){
        var options = {
            twitter: {
            text: '',
            via: ''
        },
        facebook : true,
        googlePlus : true
        };
        $('.socialShare').shareButtons(options);
    });
</script>
<!-- scroll-up-bottom -->
<script type="text/javascript">
    $(document).ready(function() {
        $.apScrollTop({'onInit': function(evt) {console.log('apScrollTop: init');}});
    });
</script>
{% endblock %}
{% block scripts2 %}
{% endblock scripts2 %}
<script>
$(function () {
    var options = {
    url: 'originalUrl'};
        $('.images').viewer(options);
});

</script>
<noscript>
    <img src="//piwik.apollo.arz.oeaw.ac.at/piwik.php?idsite=48" style="border:0;" alt=""/>
</noscript>
</body>
</html>

webpage/templates/webpage/base_b4.html
<!DOCTYPE html>
{% load staticfiles %}
{% load webpage_extras %}
{% load browsing_extras %}
<html lang="en">
<head>
<meta charset="utf-8">
       <meta charset="utf-8">
    <title>{% block title %} {% projects_metadata 'title' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metaDescription %}
        <meta name="description" content="{{ metadata.description }}">
        <meta name="author" content="{{ metadata.author }}">
    {% endblock %}
    <!-- favicons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'webpage/img/favicon/apple-touch-icon.png' %}"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'webpage/img/favicon/favicon-32x32.png' %}"/>
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'webpage/img/favicon/favicon-16x16.png' %}"/>
        <link rel="manifest" href="{% static 'webpage/img/favicon/manifest.json' %}"/>
        <link rel="mask-icon" href="{% static 'webpage/img/favicon/safari-pinned-tab.svg' %}" color="#00aba9"/>
        <meta name="theme-color" content="#ffffff"/>
    <!--favicons end -->
      <!-- Bootstrap -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/bootstrap400/css/bootstrap.min.css' %}"/></link>
      <!-- custom css -->
    <!-- <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}" /> -->

      <!--scroll to top CSS -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}"></link>
      <!-- jQuery -->
        <script type="text/javascript" src="{% static 'webpage/libraries/jquery/jquery.js' %}"></script>
<link href="https://fundament.acdh.oeaw.ac.at/dist/fundament/css/fundament.min.css" rel="stylesheet">


<!--scroll to top -->
    <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
    <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
    <script type="text/javascript">
        window.cookieconsent_options = {
            "message":"This website uses cookies to ensure you get the best experience on our website",
            "dismiss":"Got it!",
            "learnMore":"More info",
            "link":"{% url 'webpage:staticpage' template='imprint' %}",
            "theme":"dark-bottom"};
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
    <!-- End Cookie Consent plugin -->
    <!-- cool-share plugin http://tutorialzine.com/2014/08/cool-share-jquery-plugin/ -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/cool-share/plugin.css' %}" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
     

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
             <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About
                  <span class="caret"/>
                  </a>
                 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'webpage:staticpage' template='about' %}">About project</a>
                    <a class="dropdown-item" href="{% url 'webpage:staticpage' template='imprint' %}">Imprint | Impressum</a>
                </div>
              </li>
             
            
            <ul class="navbar-nav ml-auto">
                    
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                {{ user.get_username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="nav-link" href="{% url 'webpage:user_logout' %}">Log Out</a>
                            </div>
                          </li>
                        {% else %}
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'webpage:user_login' %}">Log In</a>
                         </li>  
                        {% endif %}
                    
                </ul>
        </div>
    </nav>
</header>
<section class="main-content">
    <div id="content" class="container">
        <div class="alert alert-warning alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Warning!</strong> Draft Version.
        </div>
        {% block content %}{% endblock %}
    </div>
</section>
<footer>
</footer>
<script defer src="https://fundament.acdh.oeaw.ac.at/dist/fundament/vendor/js/fontawesome-all.min.js"></script>
<script src="https://fundament.acdh.oeaw.ac.at/dist/fundament/vendor/js/jquery.min.js"></script>
<script src="https://fundament.acdh.oeaw.ac.at/dist/fundament/js/fundament.min.js"></script>
</body>
</html>

webpage/templates/webpage/contact.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block title %} Kontakt {% endblock %}
{% block content %}
<!-- end header -->
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <ul class="breadcrumb">
        <li><a href="{% url 'webpage:start' %}"><i class="fa fa-home" style="color:white"></i></a><i class="icon-angle-right"></i></li>
        <li class="active">Kontakt</li>
      </ul>
    </div>
  </div>
</div>

<div class="container" style="margin-top:25px; margin-bottom:50px;">
  <div class="row">
    <div class="col-lg-12">
      <div class="row">


        <div class="col-lg-8 mb-4">
          <!-- Embedded Google Map -->
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2658.4970102118264!2d16.374823150931338!3d48.21630355355204!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x476d07a6a3c8fc19%3A0x665ef9d097c41b38!2sHollandstra%C3%9Fe+11%2C+1020+Wien!5e0!3m2!1sde!2sat!4v1520184683758" width="100%" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        <div class="col-lg-4">

          <div class="box-gray">
            <h2>Kontaktinformationen</h2>
            <hr width="10%">
            <p>
              <b>Dr. Mario Gavranovic</b> <br>
              OREA Institut für Orientalische und Europäische Archäologie<br>
              Akademie der Wissenschaften<br>
              Hollandstrasse 11-13, 1020 Wien, Österreich
              <br>
            </p>
            <p>
              <abbr title="Email">E</abbr>:
              <a href="mailto:mario.gavranovic@oeaw.ac.at ">mario.gavranovic@oeaw.ac.at
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>



{% endblock %}

webpage/templates/webpage/database.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block title %} Kleinfunde DB{% endblock %}
{% block content %}
<!-- end header -->
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <ul class="breadcrumb">
        <li><a href="{% url 'webpage:start' %}"><i class="fa fa-home" style="color:white"></i></a><i class="icon-angle-right"></i></li>
        <li class="active">Kleinfunde DB</li>
      </ul>
    </div>
  </div>
</div>

<div class="container" style="margin-top:25px;">
  <div class="row">
    <div class="col-lg-12">
      <div class="row">

        <div class="col-lg-12">
          <div class="box-gray">
            <h2>Kleinfundedatenbank</h2>
            <hr width="10%">
            <br>
            <p>Das Projekt „Kleinfundedatenbank“ stellt gewissermassen den Beginn der Digitalisierungsarbeit des Spätbronzezeitlichen Fundmateriales der Grabungen in Thunau dar. Das Scanprojekt wurde von Dr. Michaela Lochner in Auftrag gegeben und von Melanie Zeller von 2012-2015 durchgeführt,  wobei über 74500 Datensätze erstellt wurden. . Ziel des Projektes war eine übersichtliche Aufbereitung der Funde aus allen Grabungskampagnen in Thunau am Kamp, damit sie für die Beantwortung zukünftiger Fragestellungen herangezogen werden können. Der Fokus lag dabei auf Funden aus der Spätbronzezeit.
            </p>
            <p>
              Dazu wurden die Zeichnungen der Funde – die bis dahin nur in analoger Form vorlagen – eingescannt und mit dem entsprechenden Datensatz in einer Access-Datenbank verlinkt. Die Datenbank „Fundprotokoll“ bestand bereits, war jedoch nur spärlich ausgefüllt. Im Zuge des Projektes wurde die Datenbank um die Attribute Datierung, Grundform, Material, Anmerkung und ScanPfad erweitert. Die Zeichnungen  wurden anhand ihrer Fundnummern einem Datensatz in der Tabelle zugeordnet, die oben erwähnten Attribute bestimmt und die eingescannte Bleistift- oder Tusche-Zeichnung wurde durch einen Hyperlink mit dem zugehörigen Datensatz verlinkt. Auf diese Weise wurden Funde aller Materialgattungen aus verschiedenen Fundstellen in Thunau am Kamp sowie aus dem Gräberfeld Inzersdorf aufbereitet. Auch Artefakte aus den Museen Horn, Eggenburg, Gars, Traismauer und der Prähistorischen Abteilung des Naturhistorischen Museums in Wien wurden erfasst.
            </p>
            <p>
              Die Tabelle FUNDPRO enthält den Großteil der Funde während für die Artefakte aus dem Gräberfeld Inzersdorf eine eigene Tabelle angelegt wurde. Um die Fundnummern als Primärschlüssel verwenden zu können wurden für die Objekte aus dem Museum Horn, sowie für jene der Fundstelle Thunau  Goldberggasse eigene Tabellen angelegt.
            </p>
            <p>
              Die eingescannten Zeichnungen wurden als TIF-Dateien auf der Festplatte „PRÄHIST_Thunau_Scan“ abgespeichert. Sie sind in hierarchischer Reihenfolge nach Materialgruppen und Museen bzw. Fundstellen gegliedert.  Die Verzeichnisstruktur entwickelte sich erst im Laufe des Projektes, was sich als unvorteilhaft erwies. Bei zukünftigen Projekten sollte gezielt darauf geachtet werden, zu Beginn einen Überblick über die Daten zu erhalten um eine geeignete Datenstruktur wählen zu können.
            </p>
            <p>
              Die erweiterte Datenbank ermöglicht nun einen schnellen Zugriff auf die Funddaten und –zeichnungen. Abfragen bezüglich Material, Form, Datierung und Fundort ermöglichen beispielsweise eine schnelle und effektive Kartierung der einzelnen Material- oder Fundgattungen.
            </p>
            <p>
               Unterteilt ist die Datenbank nach folgenden Fundkategorien:
            </p>
            <ul>
              <li>Buntmetall</li>
              <li>Eisen</li>
              <li>Keramik</li>
              <li>Knochen</li>
              <li>Stein</li>
            </ul>
            <p>Für einen vollständigen Zugan zur Datenbank kann unter folgendem Link um eine Zugangsberechtigung angesucht werden:</p>
            <i>Text: Michael Konrad, Melanie Zeller
          </div>
        </div>


      </div>
    </div>
  </div>

</div>


{% endblock %}